# Default values for base-chart.
replicaCount: 2
image:
  repository: aryanrhm/time_host
  tag: dev
  pullPolicy: IfNotPresent
service:
  name: time-host
  port: 80
  targetPort: 8000
ingress:
  host: time-host.com
